export const TranslateWeatherCondition = conditionText => {
  const conditionMap = {
    Sunny: 'Cerah',
    Clear: 'Cerah',
    'Partly cloudy': 'Sebagian Berawan',
    Cloudy: 'Berawan',
    Overcast: 'Mendung',
    Mist: 'Berkabut',
    Fog: 'Berkabut',
    'Patchy rain possible': 'Kemungkinan Hujan Ringan',
    'Patchy snow possible': 'Kemungkinan Salju Ringan',
    'Patchy sleet possible': 'Kemungkinan Hujan Es Ringan',
    'Patchy freezing drizzle possible': 'Kemungkinan Gerimis Beku Ringan',
    'Thundery outbreaks possible': 'Kemungkinan Hujan Petir',
    'Blowing snow': 'Salju Berhembus',
    Blizzard: 'Badai Salju',
    'Fog patches': 'Kabut Tebal',
    'Freezing fog': 'Kabut Beku',
    'Patchy light drizzle': 'Gerimis Ringan',
    'Light drizzle': 'Gerimis Ringan',
    'Freezing drizzle': 'Gerimis Beku',
    'Heavy freezing drizzle': 'Gerimis Beku Lebat',
    'Patchy light rain': 'Hujan Ringan',
    'Light rain': 'Hujan Ringan',
    'Moderate rain at times': 'Hujan Sedang Kadang-kadang',
    'Moderate rain': 'Hujan Sedang',
    'Heavy rain at times': 'Hujan Lebat Kadang-kadang',
    'Heavy rain': 'Hujan Lebat',
    'Light freezing rain': 'Hujan Beku Ringan',
    'Moderate or heavy freezing rain': 'Hujan Beku Sedang atau Lebat',
    'Light sleet': 'Hujan Es Ringan',
    'Moderate or heavy sleet': 'Hujan Es Sedang atau Lebat',
    'Patchy light snow': 'Salju Ringan',
    'Light snow': 'Salju Ringan',
    'Patchy moderate snow': 'Salju Sedang',
    'Moderate snow': 'Salju Sedang',
    'Patchy heavy snow': 'Salju Lebat',
    'Heavy snow': 'Salju Lebat',
    'Ice pellets': 'Butiran Es',
    'Light rain shower': 'Hujan Rintik Ringan',
    'Moderate or heavy rain shower': 'Hujan Rintik Sedang atau Lebat',
    'Torrential rain shower': 'Hujan Rintik Sangat Lebat',
    'Light sleet showers': 'Hujan Es Ringan',
    'Moderate or heavy sleet showers': 'Hujan Es Sedang atau Lebat',
    'Light snow showers': 'Hujan Salju Ringan',
    'Moderate or heavy snow showers': 'Hujan Salju Sedang atau Lebat',
    'Light showers of ice pellets': 'Hujan Butiran Es Ringan',
    'Moderate or heavy showers of ice pellets':
      'Hujan Butiran Es Sedang atau Lebat',
    'Patchy light rain with thunder': 'Hujan Ringan dengan Petir',
    'Moderate or heavy rain with thunder':
      'Hujan Sedang atau Lebat dengan Petir',
    'Patchy light snow with thunder': 'Salju Ringan dengan Petir',
    'Moderate or heavy snow with thunder':
      'Salju Sedang atau Lebat dengan Petir',
  };

  return conditionMap[conditionText] || conditionText; // Kembalikan teks asli jika tidak ditemukan dalam pemetaan
};
